config:
  see-own-global: true
  console-only: true
messages:
  access-denied: '&cAccess denied!'
  see-own-toggle: '&6Seeing your own global messages is now &e%value%'
  console-only: '&cThis is only for use by console!'
  prefix-set: '&6Prefix set to &e%prefix%'
  prefix-code-set: '&6Prefix &e%prefix% &6set to &e%value%'
  suffix-set: '&6Suffix set to &e%suffix%'
  invalid-player: '&cInvalid player!'
  sent: '&6Message sent to &e%player%'
  sent-global: '&6Message sent'
  console-toggle: '&6Console only now set to &e%value%'
  reloaded: '&eConfiguration reloaded'
  prefix-show: '&6Current prefix is &e%prefix%'
  no-prefix: '&6There is currently no prefix set.'
  suffix-show: '&6Current suffix is &e%suffix%'
  no-suffix: '&6There is currently no suffix set.'
  prefixlist-empty: '&6There are currently no custom prefixes.'
  prefixlist-header: '&6Current custom prefixes:'
  prefixlist-data: '&e%prefix% &7- &e%value%'
  help-prefix: '&acc :prefix &6(prefix) &7- &eSets the prefix for your messages'
  help-prefix-code: '&acc :prefix &6(:code) (prefix) &7- &eSets custom prefix for code'
  help-suffix: '&acc :suffix &6(suffix) &7- &eSets the suffix for your messages'
  help-console: '&acc :console &7- &eToggles console only restriction'
  help-send-player: '&acc &6(player) (msg) &7- &eSends msg to player'
  help-send-player-code: '&acc &6(player) (:code) (msg) &7- &eSends msg to player using prefix code'
  help-send-global: '&acc * &6(msg) &7- &eSends msg to all players'
  help-send-global-code: '&acc * &6(:code) (msg) &7- &eSends msg to all players using prefix code'
  help-reload: '&acc :reload &7- &eReloads config from disk'
  help-seeglobal: '&acc :seeglobal &7- &eToggles whether or not you see global messages you send'
  help-ccg: '&accg &6(msg) &7- &eSends msg to all players'
  help-ccg-code: '&accg &6(:code) (msg) &7- &eSends msg to all players using prefix code'
